apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lanchonete-produto-hpa
  namespace: lanchonete-produto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lanchonete-produto-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80