apiVersion: v1
kind: Service
metadata:
  name: lanchonete-produto-service
  namespace: lanchonete-produto
spec:
  selector:
    app: ds-lanchonete-produto
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer